# Generated by Django 3.2.8 on 2021-11-01 20:26

from django.db import migrations, models
import picturic.fields
import picturic.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, auto_created=True, blank=True, editable=False, unique=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, auto_created=True, blank=True, editable=False, unique=True, default=uuid.uuid4),
        ),
    ]
