# Generated by Django 3.2.8 on 2021-11-13 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picturic.fields
import picturic.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211101_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='special_for',
            field=models.TextField(blank=True, choices=[('S', 'Staff'), ('A', 'Author'), ('V', 'Vip')], default=None, help_text='This category and it\'s posts will only available for special users', max_length=1, null=True, verbose_name='Special for'),
        ),
        migrations.AddField(
            model_name='post',
            name='special_for',
            field=models.TextField(blank=True, choices=[('S', 'Staff'), ('A', 'Author'), ('V', 'Vip')], default=None, help_text='This post will only available for special users', max_length=1, null=True, verbose_name='Special for'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, auto_created=True, blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, auto_created=True, blank=True, editable=False, unique=True),
        ),
    ]
