# Generated by Django 3.2.8 on 2021-11-26 21:28

from django.db import migrations, models
import picturic.fields
import picturic.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211113_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='special_for',
            field=models.TextField(choices=[('S', 'Staff'), ('A', 'Author'), ('V', 'Vip')], default=None, help_text="This category and it's posts will only available for special users", max_length=1, null=True, verbose_name='Special for'),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_for',
            field=models.TextField(choices=[('S', 'Staff'), ('A', 'Author'), ('V', 'Vip')], default=None, help_text='This post will only available for special users', max_length=1, null=True, verbose_name='Special for'),
        ),
    ]
