# Generated by Django 3.2.9 on 2021-11-27 18:20

from django.db import migrations, models
import picturic.fields
import picturic.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211127_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='special_for',
            field=models.TextField(choices=[('S', 'Staff'), ('A', 'Author'), ('V', 'Vip'), ('N', 'Normal')], default='N', help_text="This category and it's posts will only available for special users", max_length=1, null=True, verbose_name='Special for'),
        ),
        migrations.AlterField(
            model_name='post',
            name='special_for',
            field=models.TextField(choices=[('S', 'Staff'), ('A', 'Author'), ('V', 'Vip'), ('N', 'Normal')], default='N', help_text='This post will only available for special users', max_length=1, null=True, verbose_name='Special for'),
        ),
    ]
