# Generated by Django 3.2.8 on 2021-10-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Is accepted'),
        ),
    ]
